In [4]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


Reshaping Array two 2 dimension

In [9]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1, 5)  #1, 5 represent 1 row 5 columns
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 8, 9], [1, 2, 3, 4, 5]])
print(arr2.shape)

(3, 5)


Range fun in numpy

In [11]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

np.ones and identity matrix using np.eye()

In [13]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Different numpy array operation

In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:", arr)
print("Shape:", arr.shape)
print("NUmber of Dimension:", arr.ndim)
print("Size (number of elements)", arr.size)
print("Data Type:", arr.dtype)
print("Item Size(in bytes):", arr.itemsize) #bit size of variable eg:integer = 8

Array: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
NUmber of Dimension: 2
Size (number of elements) 6
Data Type: int64
Item Size(in bytes): 8


Universal Function In Array

In [18]:
arr = np.array([1,2, 3, 4, 5])
print(np.sqrt(arr))
print(np.exp(arr))  # exp means 2.71828 to power value of array
print(np.sin(arr))
print(np.cos(arr))
print(np.log(arr))
print(np.abs(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[1 2 3 4 5]


Numpy Vectorized Operation

In [19]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 - arr2)
print(arr1 / arr2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ -9 -18 -27 -36 -45]
[0.1 0.1 0.1 0.1 0.1]


Slicing and Indexing in Array

In [25]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)
print(arr[1][2])
print(arr[1:, 2:])
print(arr[1:,1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
[[ 7  8]
 [11 12]]
[[ 6  7]
 [10 11]]


Modify Array Elements

In [30]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)
arr[0][2] = 100     #changing the value of 0 row 2 col
print(arr)
arr[1:] = 100       #changing value to 100, from colum 1 to last
print(arr)      

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[  1   2 100   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[  1   2 100   4]
 [100 100 100 100]
 [100 100 100 100]]


Statistical Concept Normaliztion

In [39]:
# normaliztion means converting data in such a way that mean is zero and standard deviation is 1

data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
std_dev = np.std(data)
normalization_data = (data - mean) / std_dev
print("Normaliztion Data:", normalization_data)

Normaliztion Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


Statistical Operations

In [40]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mean = np.mean(data)        #mean means addition of whole data divide by number of elements
print("Mean:", mean)

median = np.median(data)       #median means arranging element from least to greatest and getting middle value
print("Median:", median)

std_dev = np.std(data)      
print("Standard Deviation:", std_dev)

variance = np.var(data)
print("Variance:", variance)

#the standard deviation is a measure of the amount of variation of a random variable 
#expected about its mean. A low standard deviation indicates that the values tend to be
#close to the mean of the set, while a high standard deviation indicates that the values 
# are spread out over a wider range.



# a variance is a measure of how far a set of data (numbers) are spread out from their mean (average) value. 
# Variance means to find the expected difference of deviation from actual value.

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [11]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(data[data > 5])
print(data[(data >= 5) & (data <= 8)])
print(data[(data >= 5) | (data <= 8)])

[ 6  7  8  9 10]
[5 6 7 8]
[ 1  2  3  4  5  6  7  8  9 10]
