# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [2]:
import numpy as np
array = np.random.randint(1, 20, size=(5, 5))   #random array
print("Original Array:\n", array)

array[:, 2] = 1
print(array)

Original Array:
 [[ 8 13  1 18 13]
 [13  9 10 15 11]
 [18  3 15  2  9]
 [ 3  4  6  5  7]
 [13 12 15  4 17]]
[[ 8 13  1 18 13]
 [13  9  1 15 11]
 [18  3  1  2  9]
 [ 3  4  1  5  7]
 [13 12  1  4 17]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [16]:
array1 = np.random.randint(1, 16, size=(4, 4))
np.fill_diagonal(array1, 0)     #fill_diagonal is used to fill diagonal elements with value
print(array1)

[[ 0  6 13  3]
 [ 8  0 11  8]
 [ 3  6  0  9]
 [11 12 14  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [28]:
array1 = np.random.randint(1, 36, size=(6, 6))
print(array1)
print()

array2 = array1[2:5]
print(array2)
print()

array3 = array1[:,1:4]
print(array3)
print("---------------------------------------------")
sub_array = array1[2: 5, 1:4]
print(sub_array)

[[17  9 12 12 15 11]
 [ 9  2  4 30 18  3]
 [34 23 17 15 21  7]
 [32 16 32 15 27 20]
 [ 6  1 20  5 17 23]
 [ 5 32  6 15  2  3]]

[[34 23 17 15 21  7]
 [32 16 32 15 27 20]
 [ 6  1 20  5 17 23]]

[[ 9 12 12]
 [ 2  4 30]
 [23 17 15]
 [16 32 15]
 [ 1 20  5]
 [32  6 15]]
---------------------------------------------
[[23 17 15]
 [16 32 15]
 [ 1 20  5]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [31]:
array = np.random.randint(1, 10, size=(5, 5))
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print(border_elements)
#np.concatenate

[3 7 6 9 5 8 1 4 6 7 2 4 4 8 5 3]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [32]:
array1 = np.random.randint(1, 10, size=(3, 4))
array2 = np.random.randint(1, 10, size=(3, 4))
print(array1)
print()
print(array2)
print()
print("Addition\n:", array1+array2)
print("Substraction\n:", array1-array2)
print("Multiplication\n:", array1*array2)
print("Division\n:", array1/array2)

[[2 9 6 6]
 [1 8 7 3]
 [1 2 4 2]]

[[6 6 1 1]
 [6 7 4 5]
 [8 3 6 8]]

Addition
: [[ 8 15  7  7]
 [ 7 15 11  8]
 [ 9  5 10 10]]
Substraction
: [[-4  3  5  5]
 [-5  1  3 -2]
 [-7 -1 -2 -6]]
Multiplication
: [[12 54  6  6]
 [ 6 56 28 15]
 [ 8  6 24 16]]
Division
: [[0.33333333 1.5        6.         6.        ]
 [0.16666667 1.14285714 1.75       0.6       ]
 [0.125      0.66666667 0.66666667 0.25      ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [34]:
array1 = np.random.randint(1, 10, size=(4, 4))
row_sum = np.sum(array1, axis=1)
column_sum = np.sum(array1, axis=0)
print(row_sum)
print(column_sum)

[25 22 17 21]
[18 26 20 21]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [39]:
array1 = np.random.randint(1, 10, size=(4, 4))
mean = np.mean(array1)
median = np.median(array1)
std = np.std(array1)
variance = np.var(array1)
print(f"Mean:{mean}\nMedian:{median}\nStandard Deviation:{std}\nVariance: {variance}")

Mean:3.6875
Median:3.5
Standard Deviation:2.2836032383056386
Variance: 5.21484375


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [40]:
array1 = np.random.randint(1, 9, size=(3, 3))
mean = np.mean(array1)
std = np.std(array1)
normalized_array = (array1 - mean) / std
print(normalized_array)

[[ 1.05045146 -0.91914503  1.05045146]
 [-0.13130643 -0.91914503 -1.31306433]
 [ 1.44437076 -0.91914503  0.65653216]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add(+) a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [42]:
array1 = np.random.randint(1, 9, size=(3, 3))
row_array = np.random.randint(1, 9, size=(3, ))
print("Original Array:\n", array1)
print("Row Array:\n", row_array)
result = array1 + row_array
print("Resulting Array:\n", result)

Original Array:
 [[6 1 6]
 [2 7 4]
 [1 2 7]]
Row Array:
 [2 5 3]
Resulting Array:
 [[ 8  6  9]
 [ 4 12  7]
 [ 3  7 10]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [43]:
matrix = np.random.randint(1, 11, size=(3, 3))
print("Determinant:", np.linalg.det(matrix))
print("Inverse:", np.linalg.inv(matrix))
print("Eigenvalues:", np.linalg.eigvals(matrix))

Determinant: -35.00000000000001
Inverse: [[-1.42857143  2.08571429 -0.8       ]
 [-0.          0.2        -0.2       ]
 [ 0.42857143 -0.68571429  0.4       ]]
Eigenvalues: [18.31196011 -0.77576054  2.46380043]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [45]:
array1 = np.random.randint(1, 10, size=(2, 3))
array2 = np.random.randint(1, 10, size=(3, 2))
result = np.dot(array1, array2)     #np.dot() is used for matrix multiplication
print(result)   

[[138 108]
 [ 68  59]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [47]:
array1 = np.random.randint(1, 9, size=(3, 3))
array1.reshape(1, 9)
print(array1)
array1.reshape(9, 1)
print(array1)

[[4 7 3]
 [4 3 8]
 [3 6 3]]
[[4 7 3]
 [4 3 8]
 [3 6 3]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [51]:
array1 = np.random.randint(1, 9, size=(5, 5))
flatten_array = array1.flatten()
print(flatten_array)
array1 = flatten_array.reshape((5, 5))
print(array1)

[8 6 6 1 1 5 7 6 5 8 4 8 6 5 1 3 6 3 8 8 8 6 4 4 6]
[[8 6 6 1 1]
 [5 7 6 5 8]
 [4 8 6 5 1]
 [3 6 3 8 8]
 [8 6 4 4 6]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [53]:
array1 = np.random.randint(1, 9, size=(5, 5))
print(array1)
corners = array1[[0, 0, -1, -1], [0, -1, 0, -1]] #take 1 value as row from first list and first value of 2 list as column
print(corners)
#fancy indexing means printing only corener elements

[[1 8 5 1 2]
 [3 4 3 4 8]
 [4 8 6 7 3]
 [3 3 6 3 6]
 [1 3 8 4 3]]
[1 2 1 3]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [59]:
array = np.random.randint(1, 21, size=(4, 4))
array[array > 10] = 10
print(array)

[[10 10 10  1]
 [10 10 10  8]
 [10 10  6 10]
 [10 10  1 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [3]:
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original Array:\n", data)
sorted_array = np.sort(data, order='age')
print("Sorted Array:\n", sorted_array)

Original Array:
 [('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted Array:
 [('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [4]:
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean Distance:\n", distances)
# d = √[(x2 – x1)2 + (y2 – y1)2]

Euclidean Distance:
 [[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [10]:
import numpy.ma as ma

array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original Array:\n", array)
print("Masked Array:\n", masked_array)
sum_unmasked = masked_array.sum()
print("Sum of Unmasked Array:\n", sum_unmasked)

Original Array:
 [[13 14 17 15]
 [ 8 18 12  5]
 [15 13 13  1]
 [13  9 14 11]]
Masked Array:
 [[-- -- -- --]
 [8 -- -- 5]
 [-- -- -- 1]
 [-- 9 -- --]]
Sum of Unmasked Array:
 23


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [16]:
import numpy.ma as ma
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print(masked_array)

mean_masked = masked_array.mean()
masked_array = masked_array.filled(mean_masked)
print("masked_array:\n", masked_array)

[[-- 6 16]
 [19 -- 5]
 [1 6 --]]
masked_array:
 [[ 8  6 16]
 [19  8  5]
 [ 1  6  8]]
